version: '3.8'


services:
  web:
    build: ./app
    restart: unless-stopped
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  cron:
    build: ./app
    restart: unless-stopped
    env_file:
      - ./.env.dev
    depends_on:
      - db
    command: crond -f
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=spreadsheet_db
volumes:
  pgdata:
