version: "3.8"
services:
  python-script:
    build: app
    restart: always
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: docker
      DB_PASSWORD: docker
      DB_NAME: spreadsheet_db
  postgres_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: spreadsheet_db
      adminer:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  pgdata:

