# Generated by Django 4.1.1 on 2022-10-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_id', models.TextField()),
                ('usd_cost', models.FloatField()),
                ('rub_cost', models.FloatField()),
                ('delivery_date', models.DateField(null=True)),
            ],
        ),
    ]
